import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Define tus estilos profesionales (Estilo "Fintech Dashboard")
const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: 'Helvetica' },

    // Header imponente (Navy background like your FE navigation)
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#0f172a', // Navy
        padding: 20,
        margin: -40, // Extiende hasta los bordes
        marginBottom: 30,
        color: 'white'
    },
    logo: { width: 110, height: 'auto' }, // Ajusta según el tamaño de tu logo
    headerText: { alignItems: 'flex-end' },
    title: { fontSize: 22, fontWeight: 'bold', color: 'white' },
    subtitle: { fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 0.5 },

    // Contenido
    section: { marginBottom: 20, marginTop: 20 },

    // Grid de Impacto (2 columnas simétricas)
    grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },

    // Data Card con Borde de Acento (recreando el estilo FE)
    card: {
        width: '48%',
        padding: 18,
        backgroundColor: '#f8fafc', // Slate 50
        border: '1px solid #e2e8f0', // Slate 200
        borderLeftWidth: 4, // El borde de impacto
        borderRadius: 6,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
    },

    // Colores de Acento para Impacto
    accentIndigo: { borderLeftColor: '#4f46e5' }, // Disponible
    accentSlate: { borderLeftColor: '#334155' },   // Saldo Total
    accentAmber: { borderLeftColor: '#f59e0b' },   // Holds
    accentBlue: { borderLeftColor: '#3b82f6' },    // Intereses
    accentRed: { borderLeftColor: '#ef4444' },     // ND
    accentEmerald: { borderLeftColor: '#10b981' }, // NC

    // Tipografía Financiera
    label: { fontSize: 8, color: '#64748b', textTransform: 'uppercase', letterSpacing: 0.025, marginBottom: 6 },

    // Texto de Moneda (Usando colores específicos para impacto bancario)
    value: { fontSize: 18, fontWeight: 'bold' },
    textIndigo: { color: '#4f46e5' },
    textSlate: { color: '#1e293b' },
    textAmber: { color: '#b45309' },
    textBlue: { color: '#1d4ed8' },
    textRed: { color: '#b91c1c' },
    textEmerald: { color: '#047857' },

    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#94a3b8', borderTop: '1px solid #e2e8f0', paddingTop: 10 }
});

const ReportPDF = ({ data, logoUrl }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header Profesional (Navy) */}
            <View style={styles.header}>
                {/* Asegúrate de que logoUrl apunte a un PNG/JPG válido en tu carpeta public */}
                <Image style={styles.logo} src={logoUrl} />
                <View style={styles.headerText}>
                    <Text style={styles.title}>Account Consolidated Report</Text>
                    <Text style={styles.subtitle}>Report Date: {data.reportDate}</Text>
                </View>
            </View>

            {/* Contenido (Estilo Dashboard) */}
            <View style={styles.section}>
                <View style={styles.grid}>
                    <MetricPDF label="Total Available" value={data.totalAvailable} accent={styles.accentIndigo} textColor={styles.textIndigo} />
                    <MetricPDF label="Total Balance" value={data.totalBalance} accent={styles.accentSlate} textColor={styles.textSlate} />
                    <MetricPDF label="Total Holds" value={data.totalHolds} accent={styles.accentAmber} textColor={styles.textAmber} />
                    <MetricPDF label="Accrued Interest" value={data.totalAccruedInterest} accent={styles.accentBlue} textColor={styles.textBlue} />
                    <MetricPDF label="Total Debits (ND)" value={data.totalNd} accent={styles.accentRed} textColor={styles.textRed} />
                    <MetricPDF label="Total Credits (NC)" value={data.totalNc} accent={styles.accentEmerald} textColor={styles.textEmerald} />
                </View>
            </View>

            <Text style={styles.footer}>Generated by CPA FINTECH Core Banking System - CONFIDENTIAL REPORT</Text>
        </Page>
    </Document>
);

const MetricPDF = ({ label, value, accent, textColor }) => (
    <View style={[styles.card, accent]}>
        <Text style={styles.label}>{label}</Text>
        <Text style={[styles.value, textColor]}>{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0)}</Text>
    </View>
);

export default ReportPDF;